### ISSUE TITLE
只引入侧栏

### ISSUE THREAD

**Issue by caolib** [cayxc/Mdtht#11]
你好，我**只需要侧栏**，文档内容想使用其他主题，这个有办法吗

**Comment by cayxc** [comment]
您好，可以将需要修改的文档内容**部分的css样式添加到mdtht.min.css的最后**。注意如果有的样式不是生效，在对应的样式后添加： `空格!important` ， 提高其优先级。

**Comment by caolib** [comment]
谢谢了，但是感觉要改的太多了😂
