### ISSUE TITLE
请问如何高亮bat代码段

### ISSUE THREAD

**Issue by 87zrjojo** [cayxc/Mdtht#2]
找了好久终于找到这个插件了，正适合我的需求，非常感谢分享。想请问下，我想导出的html能高亮批处理bat代码，该怎么做呢？您提供的这个highlight.js不能高这bat，可否适配一下呢？我用的是typora

**Comment by cayxc** [comment]
您好，感谢您提出的问题，请重新下载一下highlight.js，下载地址： https://highlightjs.org/download  选择 “Select all languages”，然后解压文件，将解压文件中的 highlight.min.js 的代码复制到typora中。因为之前给的highlight.min.js下载地址中没有包含全部编程语言，现在readme已更新，如果可以，还请给一个star，后续会有更多更新！

**Comment by cayxc** [comment]
问题已解决
