### ISSUE TITLE
请问如何更改导出html的显示字体

### ISSUE THREAD

**Issue by 87zrjojo** [cayxc/Mdtht#3]
大神，我想更换一种显示字体，正文显示是一种字体，代码段和字用JetBrains，该如何设置呢？

**Comment by drunkenQCat** [comment]
代码段的标签是<code>，css里改code的font-family就可以了。

**Comment by cayxc** [comment]
您好，在css文件中找到 font-family 把你想要修改的字体名放在最开始就可以了

发自我的iPhone

**Comment by cayxc** [comment]
修改 css 的如下代码：

 - :root {font-family: "你的字体","PingFang SC", "Helvetica Neue", "Helvetica", "Arial", "Microsoft YaHei", "黑体", "宋体", sans-serif;}

- code{font-family: "你的代码字体" !important;}
- pre{font-family: "你的代码字体" !important;}

**后续我会再新增一个字体配置项，可以关注一下**

**Comment by 87zrjojo** [comment]
感谢大师回复，我试试先。
