### ISSUE TITLE
章节跳转需要多次点击才能到达指定位置

### ISSUE THREAD

**Issue by drunkenQCat** [cayxc/Mdtht#4]
RT。在此前的版本（MarkdownPad2AutoCatalog）中并未出现过这种问题。出问题的html在附件的压缩文件中。

[慈悲灯塔.zip](https://github.com/user-attachments/files/16301884/default.zip)

**Comment by cayxc** [comment]
抱歉啊，稍后我会测一下，到时再通知您

发自我的iPhone

**Comment by cayxc** [comment]
您好，我打开您给的html文件，并没有发现你说的问题啊，请问您是直接在html文件中使用的 mdtht.js ，还是使用的 markdow 编辑器配置的然后导出的呢，我这边试了试，好像没有发现这个问题！

**Comment by drunkenQCat** [comment]
> 
> 您好，我打开您给的html文件，并没有发现你说的问题啊，请问您是直接在html文件中使用的 mdtht.js ，还是使用的 markdow 编辑器配置的然后导出的呢，我这边试了试，好像没有发现这个问题！

直接在html使用了mdtht.min.js。我今天也再试试，可能是我电脑的问题。
