### ISSUE TITLE
大分辨率适配

### ISSUE THREAD

**Issue by huihongsoft** [cayxc/Mdtht#7]
![Snipaste_2024-08-24_21-05-11---](https://github.com/user-attachments/assets/ee1b579d-2ef6-4c12-af28-254875f918a7)

分辨率2560X1440  大佬麻烦对其他的分辨率适配一下谢谢

**Comment by cayxc** [comment]
您好，我重新做了调整，请下载最新版本，有什么问题的话再交流

**Comment by huihongsoft** [comment]
> 您好，我重新做了调整，请下载最新版本，有什么问题的话再交流

感谢大佬这么快就调整了，经尝试依然显示异常，我尝试取消@media screen and (min-width: 1921px) {
  #body-container {
    width: 100%;
    max-width: 192rem;
    margin: 0 auto;
  } 中的max-width: 192rem;会铺满正常显示，麻烦大佬再看下，谢谢
![6](https://github.com/user-attachments/assets/b32a8a40-6655-4567-bb44-ea980e58379d)
![55](https://github.com/user-attachments/assets/9e3d21a9-b8af-4dad-9384-d6b73f5bb1a4)

**Comment by cayxc** [comment]
您好，又重新做了调整。麻烦您再重新下载试试，有问题继续交流。

**Comment by cayxc** [comment]
您好，最开始是设计的页面最大宽度为1920px，超过这个宽度的整体居中显示，目前改为了2560px，您再重新下载试试，有问题继续交流。
