### ISSUE TITLE
How can I modify only the sidebar style

### ISSUE THREAD

**Issue by ClownJay** [cayxc/Mdtht#9]
This is an elegant and visually appealing HTML layout. However, I am struggling to understand how to apply these settings to only modify the HTML sidebar style without affecting the body content. Could you please advise me on how to achieve this?
Your responses are highly appreciated.

**Comment by ClownJay** [comment]
I have formatted and attempted to edit the .js and .css code with my own theme CSS settings, but I have been unsuccessful in solely modifying the HTML sidebar style. Could you please provide guidance on achieving this since I'm unfamiliar with front-end programming language?
[formatted.zip](https://github.com/user-attachments/files/17990898/formatted.zip)

**Comment by cayxc** [comment]
Hello, currently there are many areas that need to be modified for custom styles (both CSS and JS need to be modified), which are not currently supported. Relevant custom configurations may be added in the future

**Comment by cayxc** [comment]
Hello! To customize styles, it is best to have knowledge of CSS/HTML and JS. Your requirements will modify many areas (CSS and JS). More custom configurations may be added in the future.

**Comment by ClownJay** [comment]
Thank you for your response. I am eagerly anticipating the future updates for this tool. I intend to learn and implement the modifications on my own nowadays.

**Comment by cayxc** [comment]
Okay, thank you for liking it! Wishing you all the best！
